- name: create releases directory
  file:
    path: /opt/apps/frontend/releases
    state: directory
    recurse: yes
    mode: 0755

- name: remove existing symlink of previous version
  file:
    path: /opt/frontend/
    state: absent
  when: frontend.update == true

- name: download release from registry
  unarchive:
    src: "{{ frontend.release_url }}"
    dest: /opt/apps/frontend/releases/
    remote_src: yes
    mode: 0755

- name: create symlink to the deployment directory
  file:
    src: /opt/apps/frontend/releases/front-end-6.0
    dest: /opt/frontend
    state: link
    force: true

- name: copy init script for frontend
  copy:
    src: frontend
    dest: /etc/init.d/frontend
    mode: 0755

- name: install node application dependencies before start
  npm:
    path: "{{ item }}"
    state: latest
  with_fileglob:
    - /opt/frontend/front-end-6.0

- name: start frontend service
  service:
    name: frontend
    state: started
