- name: create releases directory
  file:
    path: /opt/apps/frontend/releases
    state: directory
    recurse: yes
    mode: 0755

- name: download release from registry
  unarchive:
    src: "{{ release_url }}"
    dest: /opt/apps/frontend/releases
    remote_src: yes
    mode: 0755

- name: create symlink to the deployment directory
  file:
    src: /opt/apps/frontend/releases
    dest: /opt/frontend
    state: link

- name: copy init script for frontend
  copy:
    src: frontend
    dest: /etc/init.d/frontend
    mode: 0755

- name: install node application dependencies before start
  npm:
    path: /opt/apps/frontend/releases
    state: latest

- name: start frontend service
  service:
    name: frontend
    state: started
