- name: check if the previous version of frontend is running
  find: 
    paths: /opt/frontend/
    patterns: "frontend"
  register: results

- name: delete the previous deployment if exists
  file:
    path: "{{ itme['path'] }}"
    state: absent
  with_items: "{{ results['files'] }}"

- name: create releases directory
  file:
    path: /opt/apps/frontend/releases
    state: directory
    recurse: yes
    mode: 0755

- name: download release from registry
  unarchive:
    src: "{{ release_url }}"
    dest: /opt/apps/frontend/releases
    extra_opts: [--strip-components=1]
    remote_src: yes
    mode: 0755

- name: create deployment directory
  file:
    path: /opt/frontend
    state: directory
    mode: 0755
    creates: /opt/frontend

- name: create symlink to the deployment directory
  file:
    src: /opt/apps/frontend/releases
    dest: /opt/frontend
    state: link
    force: true

- name: copy init script for frontend
  copy:
    src: frontend
    dest: /etc/init.d/frontend
    mode: 0755

- name: install node application dependencies before start
  npm:
    path: /opt/apps/frontend/releases
    state: latest

- name: start frontend service
  service:
    name: frontend
    state: started
