---
# filename: roles/mysql/tasks/configure.yml
 - name: create mysql config
   template: src="my.cnf.j2" dest="{{ mysql['config']['cnfpath'] }}" mode=0644
   notify:
    - restart mysql service
   tags:
    - configure

 - name: start mysql service
   service:
     name: mysql
     state: started
   tags:
    - configure

- vars: 
    msg: | 
           GROUPS Variables ("groups"):
        --------------------------------
        {{ groups | to_nice_json }}

 - name: create mysql databases
   mysql_db:
     name: "{{ item.name }}"
     state: "{{ item.state }}"
   with_dict: "{{ mysql['databases']['db1'] }}"
   tags:
    - configure 

 - name: create mysql users
   mysql_user:
     name: "{{ item.name }}"
     host: "{{ item.host }}"
     password: "{{ item.pass }}"
     priv: "{{ item.priv }}"
     state: "{{ item.state }}"
   with_dict: "{{ mysql['users']['user1'] }}"
   tags:
    - configure
